name: Deploy to Azure VM

on:
push:
branches:
- main 

jobs:
deploy:
runs-on: ubuntu-latest

steps:
- name: Checkout code
uses: actions/checkout@v3

- name: Set up SSH key
run: |
mkdir -p ~/.ssh
echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa
ssh-keyscan -H ${{ secrets.VM_PUBLIC_IP }} >> ~/.ssh/known_hosts

- name: Deploy files to VM
run: |
rsync -avz --delete ./ \
azureuser@${{ secrets.VM_PUBLIC_IP }}:/var/www/healthcare \
-e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"

- name: Restart Nginx
run: |
ssh azureuser@${{ secrets.VM_PUBLIC_IP }} \
-i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
"sudo systemctl restart nginx"
